<a href="https://colab.research.google.com/github/Namyalg/Projects_in_python/blob/master/Convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import PIL

In [0]:
from google.colab.patches import cv2_imshow


In [171]:
import numpy as np
import cv2

# Load an color image in grayscale
img = cv2.imread('/content/Lion.JPG',0)


img = cv2.resize(img, (300, 360))
cv2_imshow(img)

(360, 300)


In [172]:
sharpen = np.array([0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11]).reshape(3,3)
print(sharpen)

[[0.11 0.11 0.11]
 [0.11 0.11 0.11]
 [0.11 0.11 0.11]]


In [173]:
pixels = []
for i in range(360):
  for j in range(300):
    pixels.append(img[i,j])

pixels = np.array(pixels).reshape(360,300)
pixels = np.insert(pixels , [0,360] , np.zeros(len(pixels[0])) , axis = 0)
pixels = np.insert(pixels , [0,300] , np.zeros((len(pixels[:, 0]) ,1)) , axis = 1)
print(pixels.shape)

reduced = []
for i in range(1,360):
  for j in range(1,300):
    d = pixels[i:i+3 , j:j+3]
    m = np.multiply(d,sharpen)
    reduced.append(sum(sum(m)))
  
reduced = np.array(reduced).reshape(359,299)

(362, 302)


In [0]:
import numpy as np
from PIL import Image
array = (reduced).astype(np.uint8)
img = Image.fromarray(array)
img.save('blur.jpg')